(function(){
var DB="https://home-dashboard-61d63-default-rtdb.europe-west1.firebasedatabase.app";
var state={shopping:{},tasks:{},events:{}};
function el(x){return document.getElementById(x)}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function req(method,path,data,cb){
 var x=new XMLHttpRequest(); x.onreadystatechange=function(){if(x.readyState===4){if(x.status>=200&&x.status<300){el("sync").className="sync ok";el("sync").innerHTML="● Sincronizado";if(cb)cb(x.responseText)}else{el("sync").className="sync bad";el("sync").innerHTML="● Erro de sincronização"}}};
 x.open(method,DB+"/"+path+".json",true);x.setRequestHeader("Content-Type","application/json");x.send(data===null?null:JSON.stringify(data));
}
function id(){return "i"+(new Date().getTime())+"_"+Math.floor(Math.random()*100000)}
function loadAll(){req("GET","dashboard",null,function(t){try{var d=JSON.parse(t)||{};state.shopping=d.shopping||{};state.tasks=d.tasks||{};state.events=d.events||{};render()}catch(e){}})}
function renderList(target,obj,type){var a=[],k;for(k in obj)if(obj.hasOwnProperty(k))a.push({id:k,t:obj[k].text||"",done:!!obj[k].done});var o="";for(var i=0;i<a.length;i++)o+='<div class="row '+(a[i].done?"done":"")+'"><input class="check" type="checkbox" data-type="'+type+'" data-id="'+a[i].id+'" '+(a[i].done?"checked":"")+'><span class="txt">'+esc(a[i].t)+'</span><button class="remove" data-remove="'+type+'" data-id="'+a[i].id+'">×</button></div>';el(target).innerHTML=o}
function niceDate(s){var p=s.split("-"),d=new Date(+p[0],+p[1]-1,+p[2]),ds=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"],ms=["jan","fev","mar","abr","mai","jun","jul","ago","set","out","nov","dez"];return ds[d.getDay()]+", "+d.getDate()+" "+ms[d.getMonth()]}
function renderEvents(){var a=[],k;for(k in state.events)if(state.events.hasOwnProperty(k)){var e=state.events[k];e._id=k;a.push(e)}a.sort(function(a,b){return(a.date+a.time).localeCompare(b.date+b.time)});var o="",last="";for(var i=0;i<a.length;i++){if(a[i].date!==last){last=a[i].date;o+='<div class="eventDate">'+niceDate(last)+'</div>'}o+='<div class="event"><span class="time">'+esc(a[i].time)+'</span><span class="dot '+esc(a[i].who)+'"></span><span>'+esc(a[i].text)+'</span><button class="remove" data-remove="events" data-id="'+a[i]._id+'">×</button></div>'}el("events").innerHTML=o||'<div style="padding:20px;color:#777">Sem eventos.</div>'}
function render(){renderList("shopping",state.shopping,"shopping");renderList("tasks",state.tasks,"tasks");renderEvents()}
document.body.onclick=function(e){var t=e.target,type=t.getAttribute("data-type"),rid=t.getAttribute("data-id"),rem=t.getAttribute("data-remove");if(type&&t.type==="checkbox"){var v=!!t.checked;state[type][rid].done=v;req("PATCH","dashboard/"+type+"/"+rid,{done:v});render()}if(rem){delete state[rem][rid];req("DELETE","dashboard/"+rem+"/"+rid,null);render()}};
function bindAdd(form,input,type){el(form).onsubmit=function(e){e.preventDefault();var x=el(input),v=x.value.replace(/^\s+|\s+$/g,"");if(v){var k=id(),item={text:v,done:false};state[type][k]=item;req("PUT","dashboard/"+type+"/"+k,item);x.value="";render()}return false}}
bindAdd("shoppingForm","shoppingInput","shopping");bindAdd("taskForm","taskInput","tasks");
function pad(n){return n<10?"0"+n:""+n}
function fillSelects(){var d=new Date(),i;for(i=1;i<=31;i++)el("day").options.add(new Option(i,i));var mons=["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];for(i=0;i<12;i++)el("month").options.add(new Option(mons[i],i+1));for(i=d.getFullYear();i<=d.getFullYear()+4;i++)el("year").options.add(new Option(i,i));for(i=0;i<24;i++)el("hour").options.add(new Option(pad(i),pad(i)));for(i=0;i<60;i+=5)el("minute").options.add(new Option(pad(i),pad(i)));el("day").value=d.getDate();el("month").value=d.getMonth()+1;el("year").value=d.getFullYear();el("hour").value=pad(d.getHours());el("minute").value="00"}
fillSelects();var modal=el("modal");el("showEvent").onclick=function(){modal.style.display="block"};el("closeEvent").onclick=function(){modal.style.display="none"};
el("eventForm").onsubmit=function(e){e.preventDefault();var text=el("eventText").value.replace(/^\s+|\s+$/g,"");if(!text)return false;var date=el("year").value+"-"+pad(+el("month").value)+"-"+pad(+el("day").value),time=el("hour").value+":"+el("minute").value,k=id(),item={date:date,time:time,text:text,who:el("who").value};state.events[k]=item;req("PUT","dashboard/events/"+k,item);el("eventText").value="";modal.style.display="none";render();return false};
var days=["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"],months=["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"];
function tick(){var d=new Date(),h=d.getHours(),m=d.getMinutes();el("greet").innerHTML=h<12?"Bom dia!":h<20?"Boa tarde!":"Boa noite!";el("dateText").innerHTML=days[d.getDay()]+", "+d.getDate()+" de "+months[d.getMonth()];el("clock").innerHTML=pad(h)+":"+pad(m)}tick();setInterval(tick,30000);
function wi(c){return c===0?"☀":c<=3?"⛅":c<=48?"☁":c<=67?"🌧":c<=77?"❄":c<=82?"🌦":"⛈"}
var w=new XMLHttpRequest();w.onreadystatechange=function(){if(w.readyState===4&&w.status>=200&&w.status<300){try{var j=JSON.parse(w.responseText),o='<div class="days">',n=["Hoje","Amanhã","Depois"];for(var i=0;i<3;i++)o+='<div class="day"><b>'+n[i]+'</b><div class="icon">'+wi(j.daily.weather_code[i])+'</div><div class="temp">'+Math.round(j.daily.temperature_2m_max[i])+'°</div><small>mín. '+Math.round(j.daily.temperature_2m_min[i])+'°</small></div>';el("forecast").innerHTML=o+"</div>"}catch(e){}}};w.open("GET","https://api.open-meteo.com/v1/forecast?latitude=39.2362&longitude=-8.6859&daily=weather_code,temperature_2m_max,temperature_2m_min&timezone=Europe%2FLisbon&forecast_days=3",true);w.send();
loadAll();setInterval(loadAll,5000);
})();